### ISSUE TITLE
Have you done backend for this??

### ISSUE THREAD

**Issue by Appanavenkatasaicharan** [iahmad16/Food-Delivery-Front-End#1]

**Comment by iahmad16** [comment]
@Appanavenkatasaicharan I haven't. The video tutorial I mentioned is for the frontend, but there is a backend tutorial recently posted on GreatStack's channel.

**Comment by Appanavenkatasaicharan** [comment]
@iahmad16   Are you planning on continuing the tutorial?

**Comment by iahmad16** [comment]
@Appanavenkatasaicharan I'm not sure. I might do it later but these projects that I uploaded here are just for building my profile and also a means of learning new things which in this case was React. Also just to make it clear the tutorial is not mine, it's someone else's (Youtube: GreatStack).

**Comment by Appanavenkatasaicharan** [comment]
Ok. let me know if you ever upload backend

**Comment by Appanavenkatasaicharan** [comment]
Tq for help
